paypal/gimel

.travis.yml
README.md

- [#8] [CI] Add CI for Gimel Build & PRs
-- .travis.yml file has been checked in with the commit
- [#35] [Docs] Improve http://gimel.readthedocs.io/
-- Added Build Passing Badge
-- Removed all documentation from README.md and referred to gimel.readthedocs.io
- [#36] [CI] Add Codacy for Gimel
- Added Docs Passing Badge
-- Apache 2 License
- Added Apache License Badge 
- Read the docs is rendering
- Badges are refreshing
- travis CI builds for this branch in my fork

[#8] [CI] Add CI for Gimel Build & PRs | [#35] [Docs] Improve http://gimel.readthedocs.io/ | [#36] [CI] Add Codacy for Gimel

---

build/gimel
build/gimel_functions
build/install_dependencies
docs/getting-started.md
docs/index.md

- Ideally we'd like to have a separate commit per issue & also PR per issue. However, in this case 2 issues are affecting same set of files & one of the two tickets is a documentation change. Hence, I'm combining these issues in 1 PR to avoid overhead.
- [#10] Adds Apache License text to build/* scripts that was missing.
- [#32] Enhance the build scripts
- [#32] update ./docs/getting-started.md to have the build scripts instead of `mvn` commands.
- Please ignore the CI failure. It will be addressed in the next PR.
At this point - integration is done with Travis CI, but the yml file is missing - which I will commit in upcoming PR.
- [#32] was validated via build script commands
```bash
build/gimel   #builds default configuration
build/gimel …
```

[#10] Add missing Apache License | [#32] Enhance the build scripts

---

CODE_OF_CONDUCT.md

[#34] Create a code of conduct doc

---

.github/PULL_REQUEST_TEMPLATE.md

This PR fixes #50 
The purpose is to alter the PR template to force PR submitters to enter a GH issue id so that when the PR is merged, the issue is automatically closed.
N/A

[#50] Auto-close GH Issue when PR is merged

---

gimel-dataapi/gimel-standalone/docker/docker-compose.yml

Fixes #55
Adding the mapping for Spark UI port 4040 in docker compose, so that users can view the queries they are running in spark-shell on Spark UI at http://localhost:4040
tested on local

[#55] [Standalone] Add Spark UI port in docker-compose

---

docs/gimel-connectors/kafka.md

Fixes #67 
https://github.com/paypal/gimel/issues/67
This is fixing the documentation errors with few kafka properties incorrectly specified in docs.
Build Succeeded.

[#67] [Docs] Fix Documentation Error for Kafka API

---

docs/index.md

https://github.com/paypal/gimel/issues/70 -> Fixing the broken link in Getting-started

[#70] [Docs] fixing the broken link in the README

---

docs/try-gimel/0-prerequisite.md

https://github.com/paypal/gimel/issues/64

[#64] [Docs] Fix Documentation errors in Gimel Quick Start related to GIMEL_HOME

---

.github/ISSUE_TEMPLATE/Bug_report.md

Fixes #85 
Create issue templates for Bugs
Build Success

[#85] [Template] Create issue templates for Bugs

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Fixes #86 
- Add feature request template.
- Not required

[#86] Add feature request template, fix commented lines in the bug report template.

---

docs/getting-started/gimel-pyspark-support.md

Fixes #100 
- Add python/pyspark support for Gimel.
- Share documents on how one can use Gimel in PySpark.
- Not Necessary, this only changes documentation.

[100] Add Python / Pyspark Support for Gimel

---

docs/getting-started/gimel-pyspark-support.md

Fixes #104 
- Remove the inadvertently added merge marks/comments in the readme file.
- Readme file - no testing required. 

[#104] [Bug] Remove the inadvertently added merge marks/comments in the readme file.

---

README.md

Update the link to https://gimel-dev.slack.com/x-341898137591-449590379888/reset/enQtNDUwMjMyNDM1MTg3LWUwOGFhNDlhMWQyMWY2YWEwMTM3NmVmMGM5Y2MwZThjNDdmZGE4ZWIxMGUwZGZkN2NlZjUwMGM0Mzc1ZGIyNTU which is the link to openly invite anyone to join the team.
Fixes #<issue>

[#123] Update Slack link to team invite URL

---

.gitignore
udc/udc-web/.angular-cli.json
udc/udc-web/.editorconfig
udc/udc-web/.eslintrc.json

Fixes #127 
The purpose of the PR is to fix the UDC-WEB build
The change was validated on LOCAL laptop. Please follow the instructions in the README.

[#127] [UDC] [WEB] Adding the missing angular-cli and eslint configuration

---

udc/udc-web/build/udc_ui

Fixes #133 
The purpose of the PR is to invoke UDC-WEB from any folder.
The change was validated in local environment

[#133] [UDC] [WEB] Invoke UDC-WEB build from any directory

---

udc/udc-web/quickstart/start_udc_ui

Fixes #135 
The purpose of the PR is to remove user prompts in installing udc-web on a docker container
The change was validated on local environment

[#135][UDC][WEB] Removing user Prompt from installing udc-web image

---

udc/README.md

#138 
The purpose of the PR is to add a consolidated README for udc-web and udc-serv
N/A

[#138] [UDC] Adding README at udc level

---

mkdocs.yml

Fixes #<issue>
[#140] Add mkdocs yaml file to render readthedocs theme
Before:
After:

[#140] Add mkdocs yml file to render readthedocs theme

---

docs/gimel-connectors/teradata.md

GitHub Issue
Fixes #143 
This updates the Teradata documentation.
N/A

[#143] [Documentation] Updating Teradata docs.

---

docs/index.md

Fixes #148 
The purpose of the PR is to add UDC reference to the parent
The change was validated in local environment

[#148] [UDC]Adding UDC reference in the index

---

gimel-logging/pom.xml

Fixes #137 
- Fix the security vulnerability
- Build Succeeded

[#137] [Security] Fix the Security Alert

---

pom.xml

Fixes #<154>
- Fix Security Vulnerability
- Updated repo protocol to https

[#154] [SECURITY] Releases are built/executed/released in the context of insecure/untrusted code

---

docs/gimel-connectors/teradata.md
gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/conf/JdbcConfigs.scala
gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/utilities/JDBCAuthUtilities.scala
gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/utilities/JDBCCommons.scala
pom.xml

[#156][Enhancement] Feature to read password from user rather than from HDFS file

---

gimel-dataapi/gimel-connectors/gimel-elasticsearch-6.2/pom.xml
gimel-dataapi/gimel-connectors/gimel-elasticsearch-6.2/src/main/scala/com/paypal/gimel/elasticsearch/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-elasticsearch-6.2/src/main/scala/com/paypal/gimel/elasticsearch/conf/ElasticSearchConfigs.scala
gimel-dataapi/gimel-connectors/gimel-elasticsearch-6.2/src/main/scala/com/paypal/gimel/elasticsearch/conf/ElasticSearchConstants.scala
gimel-dataapi/gimel-connectors/gimel-elasticsearch-6.2/src/main/scala/com/paypal/gimel/elasticsearch/utilities/ElasticSearchUtilities.scala
gimel-dataapi/gimel-core/pom.xml
gimel-dataapi/pom.xml

Fixes #172
Upgrade ES version to 6.2
Spark-shell

[#172] Upgrade ES version to 6.2

---

docs/index.md
gimel-dataapi/pom.xml
gimel-logging/gimel-logging_2.0/pom.xml
gimel-logging/gimel-logging_2.3/pom.xml
gimel-logging/gimel-logging_2.3/src/main/scala/com/paypal/gimel/logging/GimelSparkListener.scala
gimel-logging/gimel-logging_2.3/src/main/scala/com/paypal/gimel/logging/GimelStreamingListener.scala
gimel-logging/pom.xml
gimel-logging/src/main/java/com/paypal/gimel/logging/LogProvider.java
gimel-logging/src/main/java/com/paypal/gimel/logging/impl/BaseLogger.java
gimel-logging/src/main/java/com/paypal/gimel/logging/utils/Configuration.java
gimel-logging/src/main/java/com/paypal/gimel/logging/utils/Utilities.java
gimel-logging/src/main/resources/log4j.properties
gimel-logging/src/main/resources/scaasConfig.properties
gimel-logging/src/main/scala/com/paypal/gimel/logging/Logging.scala

Fixes #174 
Upgrade gimel-logging module to spark 2.3.0

[#174] Upgrade the spark version in gimel_logging to 2.3.0

---

docs/gimel-connectors/hbase.md
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/conf/GimelConstants.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/gimelservices/payload/AutoRegisterObject.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/gimelservices/payload/Dataset.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/gimelservices/payload/ObjectSchemaMapUploadOutput.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/storageadmin/HBaseAdminClient.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/utilities/GenericUtils.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/pom.xml
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/conf/HbaseClientConfiguration.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/conf/HbaseConstants.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/utilities/HBaseCatalog.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/utilities/HBaseLookUp.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/utilities/HBasePut.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/utilities/HBaseScanner.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/utilities/HBaseSparkConnector.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/utilities/HBaseUtilities.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/test/scala/com/paypal/gimel/hbase/DataSetTest.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/test/scala/com/paypal/gimel/hbase/utilities/HBaseCatalogTest.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/test/scala/com/paypal/gimel/hbase/utilities/HBaseLocalClient.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/test/scala/com/paypal/gimel/hbase/utilities/HBaseLookUpTest.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/test/scala/com/paypal/gimel/hbase/utilities/HBasePutTest.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/test/scala/com/paypal/gimel/hbase/utilities/HBaseSparkConnectorTest.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/test/scala/com/paypal/gimel/hbase/utilities/HBaseUtilitiesTest.scala
gimel-dataapi/gimel-core/src/main/scala/com/paypal/gimel/DataSet.scala
gimel-dataapi/pom.xml

Fixes #179 
- Limit push down to hbase SHC connector by setting spark.hbase.connector.pageSize parameter
- Better Configuration management for HBase API
- Add Unit Test Cases
Spark shell

 Refactor HBase API and add Limit pushdown to hbase

---

docs/gimel-connectors/hbase.md
gimel-dataapi/gimel-common/pom.xml
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/gimelservices/GimelServiceUtilities.scala
gimel-dataapi/gimel-common/src/test/scala/com/paypal/gimel/common/utilities/GimelServiceUtilitiesTest.scala

Fixes #181 
Dynamic Dataset support for HBase
Spark Shell

[#181] Dynamic Dataset for hbase

---

docs/gimel-connectors/fields-bind-to.md
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/conf/GimelConstants.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/utilities/BindToFieldsUtils.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/utilities/FieldsJsonProtocol.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/utilities/SQLDataTypesUtils.scala
gimel-dataapi/gimel-common/src/test/scala/com/paypal/gimel/common/utilities/BindToFieldsUtilsTest.scala
gimel-dataapi/gimel-common/src/test/scala/com/paypal/gimel/common/utilities/SQLDataTypesUtilsTest.scala
gimel-dataapi/gimel-connectors/gimel-kafka-0.10-2/src/main/scala/com/paypal/gimel/kafka2/conf/KafkaClientConfiguration.scala
gimel-dataapi/gimel-connectors/gimel-kafka-0.10-2/src/main/scala/com/paypal/gimel/kafka2/reader/KafkaBatchConsumer.scala
gimel-dataapi/gimel-connectors/gimel-kafka-0.10-2/src/test/scala/com/paypal/gimel/kafka2/reader/KafkaBatchConsumerTest.scala
gimel-dataapi/gimel-connectors/gimel-kafka-0.10/src/main/scala/com/paypal/gimel/kafka/conf/KafkaClientConfiguration.scala
gimel-dataapi/gimel-connectors/gimel-kafka-0.10/src/main/scala/com/paypal/gimel/kafka/reader/KafkaBatchConsumer.scala
gimel-dataapi/gimel-connectors/gimel-kafka-0.10/src/main/scala/com/paypal/gimel/kafka/utilities/KafkaUtilities.scala
gimel-dataapi/gimel-core/src/main/scala/com/paypal/gimel/DataSet.scala

Fixes #196 
Add option to select additional/missing columns in gimel Data API/GSQL
Handle the bug for avro schema source options CSR and INLINE in Kafka API
Spark shell
```
import org.apache.spark.sql.{Column, Row, SparkSession,DataFrame}
import org.apache.spark.sql.functions._
// Create Gimel SQL reference
val gsql: (String) => DataFrame = com.paypal.gimel.sql.GimelQueryProcessor.executeBatch(_: String, spark)
gsql("set gimel.logging.level=CONSOLE")
val dataset = com.paypal.gimel.DataSet(spark)
val fieldsBindToString=s"""[{"fieldName":"name","fieldType":"string","defaultValue":"null"},{"fieldName":"age","fieldType":"string","defaultValue":"null"}, {"fieldName":"address","fieldType":"string","defaultValue":""} ]"""
val options = …
```

[#196] Bind to fields provided by user and add additional/missing columns as part of dataset.read

---

docs/gimel-connectors/teradata.md
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/conf/GimelConstants.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/security/AuthProvider.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/utilities/GenericUtils.scala
gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/conf/JdbcConfigs.scala
gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/conf/JdbcConstants.scala
gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/utilities/JDBCAuthUtilities.scala

Fixes #199 
Add custom AuthProvider for getting JDBC credentials
Spark shell

[#199] Add custom AuthProvider for getting JDBC credentials

---

gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/conf/GimelConstants.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/utilities/RandomGenerator.scala
gimel-dataapi/gimel-common/src/test/scala/com/paypal/gimel/common/utilities/RandomGeneratorTest.scala
gimel-dataapi/gimel-sql/src/main/scala/com/paypal/gimel/sql/GimelQueryUtils.scala
gimel-dataapi/gimel-sql/src/test/scala/com/paypal/gimel/sql/GimelQueryUtilsTest.scala

Fixes #202 
Make tmp table name random and remove conflict between dataset names in GSQL.
Spark shell

[#202] Randomize tmp table names created in GSQL logic

---

gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/datasetfactory/GimelDataSet.scala
gimel-dataapi/gimel-connectors/gimel-aerospike-3.14/src/main/scala/com/paypal/gimel/aerospike/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-cassandra-2.0/src/main/scala/com/paypal/gimel/cassandra/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-druid-0.82/src/main/scala/com/paypal/gimel/druid/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-elasticsearch-6.2/src/main/scala/com/paypal/gimel/elasticsearch/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-hbase-1.2/src/main/scala/com/paypal/gimel/hbase/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-hive-1.2/src/main/scala/com/paypal/gimel/hdfs/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-hive-1.2/src/main/scala/com/paypal/gimel/hive/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-hive-1.2/src/main/scala/com/paypal/gimel/hive/conf/HiveConfigs.scala
gimel-dataapi/gimel-connectors/gimel-hive-1.2/src/main/scala/com/paypal/gimel/hive/conf/HiveConstants.scala
gimel-dataapi/gimel-connectors/gimel-hive-1.2/src/main/scala/com/paypal/gimel/hive/utilities/HiveUtils.scala
gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-kafka-0.10-2/src/main/scala/com/paypal/gimel/kafka2/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-kafka-0.10/src/main/scala/com/paypal/gimel/kafka/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-restapi/src/main/scala/com/paypal/gimel/restapi/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-sftp/src/main/scala/com/paypal/gimel/sftp/DataSet.scala
gimel-dataapi/gimel-core/src/main/scala/com/paypal/gimel/DataSet.scala
gimel-dataapi/gimel-sql/src/main/scala/com/paypal/gimel/sql/GimelQueryProcessor.scala

Fixes #204 
- Add create/drop/truncate in Hive API
- Switch to HDFS API in case of cross cluster
- As Hive API requires Kerberos, we cannot access a hive table in other cluster.
- Instead, we can read files pointed by the hive table through HDFS API by using an appropriate namenode URL.
Spark shell

[#204] Add DDL support and switch for cross cluster to HDFS API in Hive API

---

gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/utilities/DataSetUtils.scala
gimel-dataapi/gimel-core/src/main/scala/com/paypal/gimel/DataSet.scala
gimel-dataapi/gimel-core/src/main/scala/com/paypal/gimel/DataStream2.scala
gimel-dataapi/gimel-sql/src/main/scala/com/paypal/gimel/sql/GimelQueryProcessor.scala
gimel-dataapi/gimel-sql/src/main/scala/com/paypal/gimel/sql/GimelQueryUtils.scala

Fixes #208 
Whenever limit clause is specified in GSQL query, set the hbase pageSize to push it down to hbase
Spark shell
```
import org.apache.spark.sql.{Column, Row, SparkSession,DataFrame}
import org.apache.spark.sql.functions._
// Create Gimel SQL reference
val gsql: (String) => DataFrame = com.paypal.gimel.sql.GimelQueryProcessor.executeBatch(_: String, spark)
gsql("set gimel.logging.level=CONSOLE")
gsql("set rest.service.method=https")
gsql("set rest.service.host=udc-service-host")
gsql("set rest.service.port=443")
// Here limit will be pushed down to HBase by setting spark.hbase.connector.pageSize
val df = gsql("select * from udc.Hbase.Test_Cluster.default.flights limit 5")
df.show
```
2. …

[#208] Push down limit to hbase in GSQL

---

docs/gimel-catalog/catalog-provider.md
docs/gimel-connectors/teradata.md
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/conf/GimelConstants.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/gimelservices/GimelServiceUtilities.scala

Fixes #218 
Add application properties and auth token in header while making GET call to UDC for fetching DatasetProperties.
spark-shell

[#218] Add app properties and auth token in header for GET calls to UDC

---

gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/conf/GimelConstants.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/conf/QueryGuardConfigs.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/query/guard/AppDiscovery.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/query/guard/AppKill.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/query/guard/AppTimer.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/query/guard/DelayedEventLoop.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/query/guard/EventLoop.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/query/guard/QueryGuard.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/query/guard/QueryGuardEvent.scala
gimel-dataapi/gimel-common/src/main/scala/com/paypal/gimel/common/query/guard/QueryGuardListener.scala
gimel-dataapi/gimel-common/src/test/scala/com/paypal/gimel/common/query/guard/ConcurrentContext.scala
gimel-dataapi/gimel-common/src/test/scala/com/paypal/gimel/common/query/guard/QueryGuardTest.scala
gimel-dataapi/gimel-sql/src/main/scala/com/paypal/gimel/sql/GimelQueryProcessor.scala

[#221] Query guard sync

---

docs/gimel-connectors/s3.md
gimel-dataapi/gimel-connectors/gimel-s3/pom.xml
gimel-dataapi/gimel-connectors/gimel-s3/src/main/scala/com/paypal/gimel/s3/DataSet.scala
gimel-dataapi/gimel-connectors/gimel-s3/src/main/scala/com/paypal/gimel/s3/conf/S3ClientConfiguration.scala
gimel-dataapi/gimel-connectors/gimel-s3/src/main/scala/com/paypal/gimel/s3/conf/S3Configs.scala
gimel-dataapi/gimel-connectors/gimel-s3/src/main/scala/com/paypal/gimel/s3/conf/S3Constants.scala
gimel-dataapi/gimel-connectors/gimel-s3/src/main/scala/com/paypal/gimel/s3/reader/S3Reader.scala
gimel-dataapi/gimel-connectors/gimel-s3/src/main/scala/com/paypal/gimel/s3/utilities/S3Utilities.scala
gimel-dataapi/gimel-connectors/gimel-s3/src/main/scala/com/paypal/gimel/s3/writer/S3Writer.scala
gimel-dataapi/pom.xml
pom.xml

Fixes #76 
Ad S3 Connector support
Spark shell

[#76] Add S3 Connector

---

.travis.yml

[CI] Skip CI for docs changes only #106
Fixes #106 
Skip CI for docs changes only

[#106][GitHub] Skip CI for docs changes only

---

gimel-logging/gimel-logging_2.2/pom.xml

Fixes #268 
This pull request fixes the dependebot alerts.
Ran dependabot plugin and verified the issues are not shown.

[#268][Security] Fix the dependabot alert

---

udc/udc-serv/quickstart/set-env

remove sensitive information for set-env file

---

udc/udc-serv/README.md
udc/udc-serv/quickstart/set-env
udc/udc-serv/src/main/resources/application-dev.properties

removed sensitive info from gimel

---

udc/udc-serv/README.md
udc/udc-serv/quickstart/set-env
udc/udc-serv/src/main/resources/application-dev.properties

remvoved sensitive info

---

udc/udc-serv/README.md
udc/udc-serv/quickstart/set-env
udc/udc-serv/src/main/resources/application-dev.properties

removed sensitive info

---

docs/gimel-connectors/restapi.md

removed senstive info from md file
